### ISSUE TITLE
The second page should not be a blank page

### ISSUE THREAD

**Issue by quixote1304629** [VolodymyrBaydalka/docxjs#69]
It can be Appear with my file

[aaa.docx](https://github.com/VolodymyrBaydalka/docxjs/files/11705363/aaa.docx)

tips： no blank pages when opening with office apps

![image](https://github.com/VolodymyrBaydalka/docxjs/assets/32378929/87bc1305-8d92-4dc7-8a42-4a7e1249de84)

**Comment by VolodymyrBaydalka** [comment]
Currently library splitting pages by section. Since fisrt page contains two sections - first with one column, second with two columns (text is white so it's not visible). With latest changes if you set `ignoreLastRenderedPageBreak` it should render it property, since your document contains `lastRenderedPageBreak` elements.

![image](https://github.com/VolodymyrBaydalka/docxjs/assets/1528799/5cae6e28-b645-4928-9df8-a36e086c9901)
